- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: klkreddy-play
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter tainee name
    private: false
  tasks:
  - name: variables at task level
  #   vars:
  #     NAME: klkreddy-task
    ansible.builtin.debug:
      msg: "Trainee name is {{NAME}}"


      # 1 preferece command line
      # 2 after command line preference is task level
      # 3 